---
title: "Gov 50 Final Project"
author: "Ty Schanhofer"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to voting in this year's Wisconsin Senate election. I want to look at it this year especially because of the concurrent Presidential election. I wonder if there are some interesting effects of the bigger, national election happening at the same time.

## Proposal Paragraph
https://www.kaggle.com/datasets/neelgajare/liberals-vs-conservatives-on-reddit-13000-posts 
  (I am moving away from my thoughts above) 
  
  Does the forum app, Reddit, give voice to more conservative or liberal viewpoints? This guiding research question was inspired by the huge role that non-traditional media sources play in politics today. As the American monolithic news culture has died, these non-traditional have become key in informing millions Americans on the political scene. I expect that conservative viewpoints would be more popular on Reddit. This hypothesis is based on the flourishing of 'fake news' rhetoric among conservatives and conservative candidates. My explanatory variables would be overall number of posts for each of the ideologies (conservatives and liberal), how many 'up votes' each post received, number of comments, etc. By gathering averages and separating data points to compare and contrast, I believe that I will be able to clearly observe whether there is a tilt towards one ideology. 'Up votes' and total number of posts for each viewpoint will be my variables of interest. The data has each row categorized by 'up votes', and I am sure I can code conservative=1/liberal=0 (or vice versa) to separate the post types and add up the total number. If I observe that the most posts/most popular posts advocate for a conservative viewpoint my hypothesis will be proven. If I observe that liberal posts are more in number and popularity my hypothesis will be disproven.
  
  
  
  
  
  
  
  